server:
  port: 9001

spring:
  kafka:
    producer:
        bootstrap-servers: kafka:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://root:pissw0rd123@springmysql:3306/sample
    #username: root
    #password: p@ssw0rd@123
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: USER-SERVICE


kafka:
  name: user_aud

