version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    networks:
      - springnetwork
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    networks:
      - springnetwork
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
networks:
  springnetwork:
    external: true
